﻿// This file was auto-generated by ML.NET Model Builder. 
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Microsoft.ML;

namespace Forecasting
{
    public partial class ForecastingFile
    {
        public static ITransformer RetrainPipeline(MLContext context, IDataView trainData)
        {
            var pipeline = BuildPipeline(context);
            var model = pipeline.Fit(trainData);

            return model;
        }

        /// <summary>
        /// build the pipeline that is used from model builder. Use this function to retrain model.
        /// </summary>
        /// <param name="mlContext"></param>
        /// <returns></returns>
        public static IEstimator<ITransformer> BuildPipeline(MLContext mlContext)
        {
            // Data process configuration with pipeline data transformations
            var pipeline = mlContext.Forecasting.ForecastBySsa(windowSize:367,seriesLength:404,trainSize:1082,horizon:10,outputColumnName:@"mod10plus1",inputColumnName:@"mod10plus1",confidenceLowerBoundColumn:@"mod10plus1_LB",confidenceUpperBoundColumn:@"mod10plus1_UB");

            return pipeline;
        }
    }
}
